### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by danieljausovec** [Marwelln/recaptcha#2]
Hi.

I added your plugin to Laravel 4.2 and get this error:

Call to undefined method Marwelln\Recaptcha\RecaptchaServiceProvider::publishes()
Line 22

What's wrong?

**Comment by Marwelln** [comment]
You need to use the v1.0.0 release if you're not using Laravel 5+.

```
"marwelln/recaptcha" : "~1.0"
```

**Comment by danieljausovec** [comment]
Thanks
